### ISSUE TITLE
anvil.tokens is undefined

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/connect-nodejs#15]
You may want to add in something like: 
```self.tokens = tokens ``` in ```connect-nodejs/index.js```
to your token function (starts around line 260)

Currently the userinfo function is trying to access ```anvil.tokens``` which does not exist.
(This is using the example code from the README)

**Comment by ikb42** [comment]
Yip!
I changed the example code and set it there, and it works, but should it be set automatically?

**Comment by christiansmith** [comment]
These methods now require you to pass an options argument with a `token` property explicitly. Using the `anvil` object itself as a "session" object worked where we were using this in the CLI, but it's not so great for a multi-user server application. 

I'll update the examples.
