### ISSUE TITLE
Example code fails at anvil.verify(JWK..)

### ISSUE THREAD

**Issue by ikb42** [anvilresearch/connect-nodejs#17]
Setting this to for example the `access_token` gives `[TypeError: Cannot read property 'indexOf' of undefined]` in a `.catch` error message.

**Comment by dmitrizagidulin** [comment]
I'm not quite understanding the problem statement here (not enough info in the description, to reproduce). I propose we close this issue (@ikb42 - feel free to reopen, if this is still relevant).

**Comment by ikb42** [comment]
The example code was failing when I was setting an unexpected value for the token, looking at the example now I'm not sure what exactly I meant / if this has changed over the time.  Will close.
