### ISSUE TITLE
AccessToken.decode doesn't exist

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/connect-nodejs#19]
Been looking around in the code as to what is generating the following error:
```Access Token verify with verifiable JWT and mismatching audience should provide an error description```

I can't find any mention of the AccessToken.decode function

I wouldn't mind taking a crack at it if you can tell me a little about what exactly it is supposed to return.

**Comment by vsimonian** [comment]
AccessToken.decode is JWT.decode from the anvil-connect-jwt library.

The error is happening due to https://github.com/kjur/jsrsasign/issues/129

**Comment by vsimonian** [comment]
Closing in favour of https://github.com/anvilresearch/connect-nodejs/issues/21
