### ISSUE TITLE
Implement client.loadClientCredentials()

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/connect-nodejs#28]
In order to use much of the Anvil-specific API (say to create users), the nodejs client needs an access token.
From talking with @christiansmith, it sounds like that token comes from one of two places:

1. A user's access token (received in the request). (Note to self: ask what sort of privileges the user must have in order to make this work? Some sort of admin role?)
2. A client’s access token obtained from the token endpoint with `client_credentials` grant (works like an API key).

In the context of `client.users.create()`, there isn't a user yet, so no access token is possible from that source. Which means, the client should be able to load that client access token. So:

Implement `client.loadClientCredentials()`:
- assumes prior client registration and a call to `.initProvider()` to load endpoints etc.
- makes a POST request to the provider's `/token` endpoint, w client_id + client_secret.
- params in the body: `grant_type=client_credentials`

For reference:
- see the implementation of client auth in models/Client.js on the [server](https://github.com/anvilresearch/connect)
- [OAuth 2.0 Client Credentials Grant specs](https://tools.ietf.org/html/rfc6749#section-4.4)
- [OIDC / Client Authentication spec](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)

**Comment by dmitrizagidulin** [comment]
Ok, turns out the `client.token()` method does this already (loads the client credentials).
Once PR #29 merges, this will be resolved.

**Comment by christiansmith** [comment]
Thanks again @dmitrizagidulin
