### ISSUE TITLE
.well-known/openid-configuration

### ISSUE THREAD

**Issue by danielbsig** [anvilresearch/connect-nodejs#7]
Hi, 

are there any plans to support the .well-known/openid-configuration endpoint of a openid connect server? It should simplify setup somewhat.

Regards,
Daníel

**Comment by christiansmith** [comment]
@danielbsig – that's a great idea. I've been planning to circle back and flesh out this lib for quite a while. Can't make promises on timing until the new docs are done. We desperately need complete, up to date docs.

Thanks!

**Comment by danielbsig** [comment]
Perhaps there are bits that could be useful here: https://github.com/IdentityModel/oidc-client. The author of that library is planning a rewrite to allow it to be both a client library as well as a server library. Maybe some collaboration could make this easier?

**Comment by danielbsig** [comment]
...when you say "we desperately need complete, up to date docs", are you referring to OpenID Connect docs?

**Comment by christiansmith** [comment]
Referring to [Anvil Connect](https://github.com/anvilresearch/connect) docs.

**Comment by christiansmith** [comment]
@danielbsig latest release includes support for .well-known/openid-configuration via `.discover()`.

**Comment by danielbsig** [comment]
Excellent, thanks!
